FROM onlyoffice/documentserver:8.3.3
RUN rm -rf /var/www/onlyoffice/documentserver/sdkjs-plugins/marketplace
COPY frontend/public/onlyoffice-plugin/ "/var/www/onlyoffice/documentserver/sdkjs-plugins/{D68097C2-7901-49BD-950E-1647893DA8A1}/"
