user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;
    server_tokens off;
    client_max_body_size 100m;

    map $http_upgrade $proxy_connection {
        default upgrade;
        ""      close;
    }
    map $http_x_forwarded_proto $the_scheme {
        default $http_x_forwarded_proto;
        ""      $scheme;
    }
    map $http_x_forwarded_host $the_host {
        default $http_x_forwarded_host;
        ""      $host;
    }

    server {
        listen 80;
        listen [::]:80;

        location /ds {
            return 301 /ds/;
        }

        location /ds/ {
            proxy_pass http://onlyoffice/;
            proxy_http_version 1.1;
            proxy_read_timeout 3600s;
            proxy_send_timeout 3600s;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $proxy_connection;
            proxy_set_header X-Forwarded-Host $the_host/ds;
            proxy_set_header X-Forwarded-Proto $the_scheme;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
        }

        location / {
            proxy_pass http://templater-backend:3053;
            proxy_http_version 1.1;
            proxy_read_timeout 3600s;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Proto $the_scheme;
        }
    }
}
